name: workflow.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: 깃헙 레파지토리 가져오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
            distribution: temurin
            java-version: 17

      - name: application.properties 파일 불러오기
        run: |
            mkdir -p src/main/resources
            echo "${{ secrets.ENV }}" > src/main/resources/.env

      - name: 빌드
        run: ./gradlew clean build -x test

      - name: 빌드 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./empty.jar

      - name: SCP로 EC2에 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: empty.jar
          target: /home/ubuntu/empty/tobe

      - name: EC2 접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/empty-project/current
            mkdir /home/ubuntu/empty-project/current
            mv /home/ubuntu/empty-project/tobe/empty.jar /home/ubuntu/empty-project/current/empty.jar
            cd /home/ubuntu/empty-project/current
            sudo fuser -k -n tcp 443 || true
            sudo nohup java -jar empty.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/empty-project/tobe